### ISSUE TITLE
`onig_sys` no longer builds, please make a new release!

### ISSUE THREAD

**Issue by Aloso** [rust-onig/rust-onig#180]
I just tried building an older project using the `onig` crate again, but it stopped working at some point. I got it working by adding this to my Cargo.toml:

```toml
[patch.crates-io]
onig_sys = { git = "https://github.com/rust-onig/rust-onig", revision = "fa90c0e97e90a056af89f183b23cd417b59ee6a2" }
```

so it is apparently fixed in the main branch, but not yet released. I would appreciate it if you published a new version so this workaround isn't needed :)
